name: Code Owners Validation
on:
  push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    steps:
    - uses: actions/checkout@v3
    - uses: mszostok/codeowners-validator@v0.7.4
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        checks: "files,owners,duppatterns,syntax,"
        experimental_checks: "notowned,avoid-shadowing"
        # owner_checker_owners_must_be_teams: true
        not_owned_checker_subdirectories: 'packages/demo/'
